### ISSUE TITLE
    -

### ISSUE THREAD

**Issue by roboserg** [lolp1/DomainWrapper#1]

**Comment by jalius** [comment]
the readme has the info for you. you need to call the exported function on your own, otherwise, like you said, the injected DLL will not do anything.

"https://github.com/lolp1/DomainWrapper/blob/master/DomainWrapper/PatchedDomainLoader.cs#L39"

**Comment by lolp1** [comment]
You need to call the export and pass a LPWSTR to it representing the path to the .net app to inject, which must in this case have an entry point such as a windows form app.

**Comment by larisoft** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Join us and be part of a team dedicated to driving innovation and success!

## How to Apply:
To apply for this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.alfredonuhe, @shangsharon, @VerheijenWebdevelopment, @mmngreco, @mattygyo, @Displee, @cencuansen, @Lordxan, @PhilippeMeyer, @alexbosworth, @ldy985, @luismanfroni, @VIPO777, @cerveeza77, @HaridRock, @jasonevrtt, @bryansayler, @kabandr, @polyzen, @4oo4
